package com.tonic.feature.practice.ui

import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onNodeWithTag
import androidx.compose.ui.test.performClick
import androidx.compose.ui.test.performScrollTo
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.tonic.core.audio.synth.SynthEngine
import com.tonic.core.model.music.Mode
import com.tonic.core.ui.theme.TonicTheme
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import kotlin.test.assertEquals
import kotlin.test.assertNotEquals
import kotlin.test.assertTrue

/**
 * Stage 2.2's second acceptance criterion — "explanation screen with worked example present and
 * reachable" (docs/20-PHASE-2-SPEC.md) — held to docs/08-UI-SPEC.md §3a's actual requirements
 * rather than to the existence of a file.
 */
@RunWith(AndroidJUnit4::class)
class M9IntroTest {
    @get:Rule
    val compose = createComposeRule()

    @Test
    fun `the explanation states what is being asked, and offers both examples and a way out`() {
        var majorPlays = 0
        var minorPlays = 0
        var started = 0

        compose.setContent {
            TonicTheme {
                M9IntroContent(
                    onPlayMajor = { majorPlays++ },
                    onPlayMinor = { minorPlays++ },
                    onStart = { started++ },
                )
            }
        }

        compose.onNodeWithTag("m9_intro").assertIsDisplayed()
        compose.onNodeWithTag("m9_intro_play_major").assertIsDisplayed()
        compose.onNodeWithTag("m9_intro_play_minor").assertIsDisplayed()
        // The explanation is longer than a phone screen and scrolls, which §3a permits - what it
        // requires is that the way out is always *reachable*, so this scrolls to it rather than
        // assuming it happens to be above the fold.
        compose.onNodeWithTag("m9_intro_start").performScrollTo().assertIsDisplayed()

        // Both examples repeatable and neither gated behind the other: switching back and forth *is*
        // the demonstration.
        compose.onNodeWithTag("m9_intro_play_major").performClick()
        compose.onNodeWithTag("m9_intro_play_minor").performClick()
        compose.onNodeWithTag("m9_intro_play_major").performClick()
        assertEquals(2, majorPlays)
        assertEquals(1, minorPlays)

        compose.onNodeWithTag("m9_intro_start").performScrollTo().performClick()
        assertEquals(1, started, "§3a: a dismiss button, always available, never gated")
    }

    @Test
    fun `the worked pair is one of each mode, generated by the real generator`() {
        val (major, minor) = M9WorkedExample.pair()

        assertEquals(Mode.MAJOR, major.mode)
        assertEquals(Mode.MINOR, minor.mode)
        assertTrue(major.elements.isNotEmpty() && minor.elements.isNotEmpty())
    }

    @Test
    fun `the two examples are audibly different, not the same audio labeled twice`() {
        // The whole explanation rests on a contrast the learner can hear. If both examples rendered the
        // same buffer - which is exactly what would happen if the generator threaded Mode.MINOR into a
        // mode-independent lookup - the screen would be teaching a distinction that does not exist in
        // the audio. Rendered through the real SynthEngine and compared sample-for-sample.
        val (major, minor) = M9WorkedExample.pair()

        fun render(item: com.tonic.core.model.items.Item.ModeIdentificationItem) =
            item.elements
                .mapIndexed { i, element -> SynthEngine.renderElement(element, seed = item.seed + 1000L * i) }
                .flatMap { it.samples.toList() }

        assertNotEquals(
            render(major),
            render(minor),
            "the major and minor examples must actually sound different",
        )
    }

    @Test
    fun `the pair is stable across calls, so the narration never describes different audio`() {
        val first = M9WorkedExample.pair()
        val second = M9WorkedExample.pair()

        assertEquals(first.first, second.first)
        assertEquals(first.second, second.second)
    }
}
